### ISSUE TITLE
OpenApi Generation only includes static paging options

### ISSUE THREAD

**Issue by macleodbroad-wf** [crnk-project/crnk-framework#589]
Regardless of how you configure your paging options, the OpenAPI Generator generates the following paging options statically:
```
    PageLimit:
      description: Max number of items
      in: query
      name: page[limit]
      schema:
        default: 100
        format: int64
        maximum: 1000
        type: integer
    PageOffset:
      description: Page offset
      in: query
      name: page[offset]
      schema:
        default: 0
        format: int64
        type: integer
```
; and does not generate `page[number]`, nor `page[size]`.

The openapi generator should take it's paging options from the `PagingSpec` and `PagingBehaviour`.
